[package]
name = "qik"
version = "0.1.0"
edition = "2024"

license = "MIT"
license-file = "LICENSE"

[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
bytes = "1.10.1"
clap = { version = "4.5.41", features = ["derive"] }
humantime = "2.2.0"
mime = "0.3.17"
owo-colors = "4.2.2"
reqwest = { version = "0.12.22", features = ["multipart", "stream", "rustls-tls", "native-tls", "socks", "cookies"] }
serde = "1.0.219"
serde_json = "1.0.142"
serde_urlencoded = "0.7.1"
tokio = { version = "1.46.1", features = ["full"] }
url = "2.5.4"
xml-rs = "0.8.27"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
serde_json = "1.0.142"
tempfile = "3.21.0"
tokio = "1.46.1"
wiremock = "0.6.5"
